- platform: group
  unique_id: bedroom_lights
  name: Bedroom Lights
  entities:
    - light.bedroom_ambient_lights
    - light.bedroom_accent_lights
    - light.bedroom_reading_light

- platform: template
  lights:
    bedroom_ambient_lights:
      unique_id: bedroom_ambient_lights
      friendly_name: "Bedroom Ambient Lights"
      value_template: "{{ is_state('switch.switch_67a8', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.switch_67a8
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.switch_67a8

- platform: group
  unique_id: bedroom_accent_lights
  name: Bedroom Accent Lights
  entities:
    - light.light_09e6_light
    - light.light_40a4_light

- platform: template
  lights:
    bedroom_reading_light:
      unique_id: bedroom_reading_light
      friendly_name: "Bedroom Reading Light"
      value_template: "{{ is_state('switch.switch_b941', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.switch_b941
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.switch_b941
      availability_template: "{{ is_state('switch.switch_b941', 'unavailable') == False }}"

- platform: group
  unique_id: bedroom_night_light
  name: Bedroom Night Light
  entities:
    - light.clock_3006_night_light
