- platform: group
  unique_id: bedroom_lights
  name: Bedroom Lights
  entities:
    - light.bedroom_ambient_lights
    - light.bedroom_accent_lights
    - light.bedroom_reading_light

- platform: group
  unique_id: bedroom_accent_lights
  name: Bedroom Accent Lights
  entities:
    - light.light_09e6
    - light.light_40a4

- platform: group
  unique_id: bedroom_decorative_lights
  name: Bedroom Decorative Lights
  entities:
    - light.bedroom_clock_light

- platform: group
  unique_id: bedroom_night_light
  name: Bedroom Night Light
  entities:
    - light.clock_3006_night_light

- platform: group
  unique_id: bedroom_clock_light
  name: Bedroom Clock Light
  entities:
    - light.clock_3006_light
