- platform: template
  lights:
    hallway_lights:
      unique_id: hallway_lights
      friendly_name: "Hallway Lights"
      value_template: "{{ is_state('switch.switch_f37c', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.switch_f37c
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.switch_f37c
      icon_template: >-
        {% if is_state('switch.hallway_lights_auto', 'on') %}
          {% if is_state('switch.switch_f37c', 'on') %}
            mdi:lightbulb-auto
          {% else %}
            mdi:lightbulb-auto-outline
          {% endif %}
        {% else %}
          {% if is_state('switch.switch_f37c', 'on') %}
            mdi:lightbulb
          {% else %}
            mdi:lightbulb-outline
          {% endif %}
        {% endif %}
