- platform: group
  unique_id: kitchen_lights
  name: "Kitchen Lights"
  entities:
    - light.kitchen_ambient_lights
    - light.kitchen_accent_lights

- platform: group
  unique_id: kitchen_ambient_lights
  name: "Kitchen Ambient Lights"
  entities:
    - light.light_9940_light_1
