# Wrapper around ION Matter dimmer due to issue
# - The dimmer wont turn on with a brightness value if the given brightness
#   value is the same as that is already set
# - The last known brightness is saved in a separate sensor entity and compared
#   to the brightness parameter in the light.turn_on action. If it is the same,
#   pass on the turn_on action without the brightness parameter.
- platform: template
  lights:
    light_ec96_wrapper:
      unique_id: light_ec96_wrapper
      value_template: "{{ is_state('light.light_ec96', 'on') }}"
      turn_on:
        if:
          - condition: template
            value_template: "{{ brightness is not none and brightness is not undefined and (brightness | int) != (states('sensor.light_ec96_last_brightness') | int) }}"
        then:
          - action: light.turn_on
            data:
              entity_id: light.light_ec96
              brightness: " {{ brightness | int }}"
        else:
          - action: light.turn_on
            data:
              entity_id: light.light_ec96
      turn_off:
        action: light.turn_off
        data:
          entity_id: light.light_ec96
      level_template: "{{ state_attr('light.light_ec96', 'brightness') }}"
      set_level:
        sequence:
          - if:
              - condition: template
                value_template: "{{ brightness is not none and brightness is not undefined and (brightness | int) != (states('sensor.light_ec96_last_brightness') | int) }}"
            then:
              - action: light.turn_on
                data:
                  entity_id: light.light_ec96
                  brightness: " {{ brightness | int }}"
            else:
              - action: light.turn_on
                data:
                  entity_id: light.light_ec96
      availability_template: "{{ is_state('light.light_ec96', 'unavailable') == False }}"
