- id: '1715778689765'
  alias: Living Room Dashboard Display Wake
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_dashboard_occupancy
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.living_room_dashboard_display
    state: 'off'
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.living_room_dashboard_display
  mode: single
- id: '1715778727157'
  alias: Living Room Dashboard Display Sleep
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_dashboard_occupancy
    to: 'off'
    for:
      seconds: '{{  states(''input_number.living_room_dashboard_display_off_delay'')|int
        }}'
  condition:
  - condition: state
    entity_id: switch.living_room_dashboard_display
    state: 'on'
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.living_room_dashboard_display
  mode: single
- id: '1715781035946'
  alias: Living Room Docked Laptop Display Sleep
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_desk_occupancy
    to: 'off'
    for:
      seconds: '{{  states(''input_number.laptop_display_off_delay'')|int }}'
  - platform: state
    entity_id:
    - switch.laptop_display
    to: 'on'
    for:
      seconds: '{{  states(''input_number.laptop_display_off_delay'')|int }}'
  condition:
  - condition: state
    entity_id: binary_sensor.laptop_docked
    state: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - condition: state
    entity_id: switch.laptop_display
    state: 'on'
    for:
      seconds: '{{  states(''input_number.laptop_display_off_delay'')|int }}'
  - condition: state
    entity_id: binary_sensor.living_room_desk_occupancy
    state: 'off'
    for:
      seconds: '{{  states(''input_number.laptop_display_off_delay'')|int }}'
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.laptop_display
  mode: single
- id: '1715781074719'
  alias: Living Room Docked Laptop Display Wake
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_desk_occupancy
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.laptop_docked
    state: 'on'
  - condition: state
    entity_id: switch.laptop_display
    state: 'off'
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.laptop_display
  mode: single
- id: '1715787983168'
  alias: Living Room TV Youtube Auto-Pause
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_occupancy
    to: 'off'
  condition:
  - condition: device
    device_id: 1c6580cf287963b48caad619f2d5a1b2
    domain: media_player
    entity_id: a4ec7014f506f908a4236dfa1ca43898
    type: is_playing
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.tv_0f54_remote
      attribute: app_id
      state: com.google.android.youtube.tv
  action:
  - service: media_player.media_pause
    metadata: {}
    data: {}
    target:
      entity_id:
      - media_player.tv_0f54_cast
      - media_player.tv_0f54_remote
  mode: single
- id: '1715788081710'
  alias: Living Room TV Youtube Auto-Play
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_occupancy
    to: 'on'
  condition:
  - condition: device
    device_id: 1c6580cf287963b48caad619f2d5a1b2
    domain: media_player
    entity_id: a4ec7014f506f908a4236dfa1ca43898
    type: is_paused
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.tv_0f54_remote
      attribute: app_id
      state: com.google.android.youtube.tv
  action:
  - service: media_player.media_play
    target:
      entity_id:
      - media_player.tv
      - media_player.tv_0f54_cast
    data: {}
  mode: single
- id: '1716473547910'
  alias: Bedroom Fan Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door
    to: 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - platform: state
    entity_id:
    - switch.bedroom_mosquito_repeller
  condition: []
  action:
  - type: turn_off
    device_id: d9f60f6e439d7d04d0a14366940cf5e4
    entity_id: c647751fa2efaef897f9c4d6b2764174
    domain: fan
  mode: single
- id: '1716715924876'
  alias: Living Room Docking Station On
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_occupancy
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.living_room_docking_station
  mode: single
- id: '1716716038346'
  alias: Living Room TV Power On
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_occupancy
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.living_room_tv_power
  mode: single
- id: '1716716274495'
  alias: Living Room TV Power Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_occupancy
    to: 'off'
    for:
      hours: 1
      minutes: 0
      seconds: 0
  condition:
  - condition: state
    entity_id: media_player.tv_0f54_remote
    state: 'off'
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.living_room_tv_power
  mode: single
- id: '1716716358957'
  alias: Living Room Docking Station Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_occupancy
    to: 'off'
    for:
      hours: 1
      minutes: 0
      seconds: 0
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: binary_sensor.laptop_docked
      state: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 0
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.living_room_docking_station
  mode: single
- id: '1717175760685'
  alias: Bedroom Fan On
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door
    to: 'off'
  - platform: state
    entity_id:
    - sensor.bedroom_iaq_index
  condition:
  - condition: state
    entity_id: binary_sensor.front_door
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.bedroom_iaq_index
    below: 50
  - condition: state
    entity_id: fan.fan_1d90
    state: 'off'
  action:
  - service: fan.turn_on
    metadata: {}
    data: {}
    target:
      device_id: d9f60f6e439d7d04d0a14366940cf5e4
  mode: single
- id: '1717181154454'
  alias: Bedroom Bedtime
  description: ''
  trigger: []
  condition: []
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.bedroom_lights
      - light.bedroom_reading_light
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.bedroom_mosquito_repeller
  - type: toggle
    device_id: d31e007475f48da84ec9406b72785700
    entity_id: 5b48a3d54783281449ca0208f1839143
    domain: switch
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.fan_1d90_night_mode
  mode: single
- id: '1719322575405'
  alias: Living Room Fan On
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_occupancy
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_occupancy
    state: 'on'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_fan_state
    data: {}
  - service: scene.delete
    target:
      entity_id: scene.living_room_fan_state
  mode: single
- id: '1719322611405'
  alias: Living Room Fan Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_occupancy
    to: 'off'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_occupancy
    state: 'off'
  action:
  - service: scene.create
    data:
      scene_id: living_room_fan_state
      snapshot_entities:
      - fan.living_room_fan
  - service: fan.turn_off
    target:
      entity_id:
      - fan.living_room_fan
    data: {}
  mode: single
- id: '1719610365051'
  alias: Bedroom Mosquito Repelling Start
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  - platform: state
    entity_id:
    - binary_sensor.front_door
  condition:
  - condition: state
    entity_id: binary_sensor.front_door
    state: 'off'
  - condition: time
    after: '21:00:00'
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.bedroom_mosquito_repeller
  mode: single
- id: '1719610469629'
  alias: Bedroom Mosquito Repelling Stop
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.bedroom_mosquito_repeller
    to: 'on'
    for:
      hours: 2
      minutes: 0
      seconds: 0
  - platform: state
    entity_id:
    - fan.fan_1d90
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.front_door
    to: 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.bedroom_mosquito_repeller
  mode: single
- id: '1721088136807'
  alias: Bedroom Buttons
  description: ''
  trigger:
  - platform: state
    entity_id:
    - event.btn_74ad_button_5_pressed
    id: btn5
  - platform: state
    entity_id:
    - event.btn_74ad_button_4_pressed
    id: btn4
  - platform: state
    entity_id:
    - event.btn_74ad_button_3_pressed
    id: btn3
  - platform: state
    entity_id:
    - event.btn_74ad_button_2_pressed
    id: btn2
  - platform: state
    entity_id:
    - event.btn_74ad_button_1_pressed
    id: btn1
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - btn1
      sequence:
      - service: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.bedroom_reading_light
    - conditions:
      - condition: trigger
        id:
        - btn2
      sequence:
      - service: light.toggle
        target:
          entity_id: light.bedroom_lights
        data: {}
    - conditions:
      - condition: trigger
        id:
        - btn3
      sequence:
      - service: automation.trigger
        target:
          entity_id: automation.bedroom_bedtime
        data:
          skip_condition: true
    - conditions:
      - condition: trigger
        id:
        - btn4
      sequence:
      - service: fan.increase_speed
        metadata: {}
        data: {}
        target:
          area_id: bedroom
    - conditions:
      - condition: trigger
        id:
        - btn5
      sequence:
      - service: fan.decrease_speed
        metadata: {}
        data:
          percentage_step: 10
        target:
          area_id: bedroom
  mode: single
- id: '1723148861587'
  alias: Living Room Desk Reading Light
  description: ''
  use_blueprint:
    path: occupancy_device.yaml
    input:
      occupancy_sensor: binary_sensor.living_room_desk_occupancy
      daylight_sensor: binary_sensor.living_room_daylight
      target_lights:
      - light.living_room_desk_reading_light
      off_delay:
        hours: 0
        minutes: 0
        seconds: 10
      temporary_scene_name: living_room_desk_reading_light_temp
      default_scene_occupied: scene.living_room_desk_reading_light_occupied
      off_delay_duration:
        hours: 0
        minutes: 0
        seconds: 10
      temporary_scene_expiration_duration:
        hours: 1
        minutes: 0
        seconds: 0
      target_entities:
      - light.living_room_desk_reading_light
- id: '1723203704306'
  alias: Kitchen Lights
  description: ''
  use_blueprint:
    path: occupancy_device.yaml
    input:
      occupancy_sensor: binary_sensor.kitchen_occupancy
      daylight_sensor: binary_sensor.kitchen_daylight
      default_scene_occupied: scene.kitchen_lights_default
      temporary_scene_name: kitchen_lights_temp
      off_delay_duration:
        hours: 0
        minutes: 1
        seconds: 0
- id: '1723205448609'
  alias: Hallway Ambient Lights
  description: ''
  use_blueprint:
    path: occupancy_device.yaml
    input:
      occupancy_sensor: binary_sensor.hallway_occupancy
      daylight_sensor: binary_sensor.hallway_daylight
      default_scene_occupied: scene.hallway_lights_default
      temporary_scene_name: hallway_lights_temp
      off_delay_duration:
        hours: 0
        minutes: 3
        seconds: 0
      temporary_scene_expiration_duration:
        hours: 0
        minutes: 0
        seconds: 0
- id: '1723219668852'
  alias: Living Room Ambient Lights
  description: ''
  use_blueprint:
    path: occupancy_device.yaml
    input:
      occupancy_sensor: binary_sensor.living_room_occupancy
      daylight_sensor: binary_sensor.living_room_daylight
      default_scene_occupied: scene.living_room_ambient_lights_default
      temporary_scene_name: living_room_ambient_lights_temp
      off_delay_duration:
        hours: 0
        minutes: 2
        seconds: 0
- id: '1723219752988'
  alias: Living Room Decorative Lights
  description: ''
  use_blueprint:
    path: occupancy_device.yaml
    input:
      occupancy_sensor: binary_sensor.living_room_occupancy
      daylight_sensor: binary_sensor.living_room_daylight
      default_scene_occupied: scene.living_room_lights_default
      temporary_scene_name: living_room_decorative_lights_temp
      off_delay_duration:
        hours: 0
        minutes: 5
        seconds: 0
- id: '1723220126869'
  alias: Living Room 3D Printer Light
  description: ''
  use_blueprint:
    path: occupancy_device.yaml
    input:
      occupancy_sensor: binary_sensor.living_room_3d_printer_occupancy
      daylight_sensor: binary_sensor.living_room_daylight
      default_scene_occupied: scene.living_room_3d_printer_light_default
      temporary_scene_name: living_room_3d_printer_light_temp
      off_delay_duration:
        hours: 0
        minutes: 0
        seconds: 10
