# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  customize_glob:
    "sensor.*_temperature":
      device_class: temperature
      icon: "mdi:thermometer"
    "sensor.*_humidity":
      device_class: humidity
      icon: "mdi:water-percent"
    "sensor.*_atmospheric_pressure":
      device_class: atmospheric_pressure
      icon: "mdi:gauge"
    "sensor.*_illuminance":
      device_class: illuminance
      icon: "mdi:brightness-5"
    "sensor.*_pm_2_5":
      device_class: pm25
      icon: "mdi:molecule"
    "sensor.*_pm_10":
      device_class: pm10
      icon: "mdi:molecule"
    "sensor.*_nitrogen_dioxide*":
      # device_class: nitrogen_dioxide
      icon: "mdi:air-filter"
    "sensor.*volatile_organic_compounds*":
      # device_class: volatile_organic_compounds
      icon: "mdi:air-filter"
    "light.*_ambient_light":
      icon: "mdi:ceiling-light"
    "light.*_ambient_lights":
      icon: "mdi:ceiling-light-multiple"
    "light.*_accent_light*":
      icon: "mdi:track-light"
    "light.*_decorative_light":
      icon: "mdi:lamp"
    "light.*_decorative_lights":
      icon: "mdi:lamps"
    "light.*_reading_light*":
      icon: "mdi:desk-lamp"
    "light.*_windowsill_light*":
      icon: "mdi:desk-lamp"
    "scene.*_ambient_light":
      icon: "mdi:ceiling-light"
    "scene.*_ambient_lights":
      icon: "mdi:ceiling-light-multiple"
    "scene.*_accent_light*":
      icon: "mdi:track-light"
    "scene.*_decorative_light":
      icon: "mdi:lamp"
    "scene.*_decorative_lights":
      icon: "mdi:lamps"
    "scene.*_reading_light*":
      icon: "mdi:desk-lamp"
    "scene.*_windowsill_light*":
      icon: "mdi:desk-lamp"

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named include/theme

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

binary_sensor: !include_dir_merge_list include/binary_sensor
sensor: !include_dir_merge_list include/sensor
light: !include_dir_merge_list include/light
template: !include_dir_merge_list include/template
input_boolean: !include_dir_merge_named include/input_boolean
input_number: !include_dir_merge_named include/input_number
switch: !include_dir_merge_list include/switch
iaquk: !include_dir_merge_named include/iaquk
fan: !include_dir_merge_list include/fan
media_player: !include_dir_merge_list include/media_player
