# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

binary_sensor: !include_dir_merge_list include/binary_sensor
sensor: !include_dir_merge_list include/sensor
light: !include_dir_merge_list include/light
template: !include_dir_merge_list include/template
input_number: !include_dir_merge_named include/input_number
switch: !include_dir_merge_list include/switch
iaquk: !include_dir_merge_named include/iaquk
fan: !include_dir_merge_list include/fan
