- platform: group
  unique_id: bathroom_mirror_light_power
  name: "Bathroom Mirror Light Power"
  entities:
    - switch.switch_8920

- platform: group
  unique_id: bathroom_mirror_heater
  name: "Bathroom Mirror Heater"
  entities:
    - switch.switch_aa60

- platform: group
  unique_id: bathroom_speaker_power
  name: "Bathroom Speaker Power"
  entities:
    - switch.switch_6ee3
