- platform: group
  unique_id: bedroom_mosquito_repeller
  name: "Bedroom Mosquito Repeller"
  entities:
    - switch.switch_2653
- platform: template
  switches:
    bedroom_lights_auto:
      unique_id: bedroom_lights_auto
      friendly_name: "Bedroom Lights Auto"
      turn_on:
        - service: automation.turn_on
          data:
            entity_id: automation.bedroom_lights_on
        - service: automation.turn_on
          data:
            entity_id: automation.bedroom_lights_off
      turn_off:
        - service: automation.turn_off
          data:
            entity_id: automation.bedroom_lights_on
        - service: automation.turn_off
          data:
            entity_id: automation.bedroom_lights_off
      value_template: >
        {{ is_state('automation.bedroom_lights_on', 'on') and is_state('automation.bedroom_lights_off', 'on') }}
      icon_template: mdi:lightbulb-auto
