- platform: template
  switches:
    kitchen_lights_auto:
      unique_id: kitchen_lights_auto
      friendly_name: "Kitchen Lights Auto"
      turn_on:
        - service: automation.turn_on
          data:
            entity_id: automation.kitchen_lights_on
        - service: automation.turn_on
          data:
            entity_id: automation.kitchen_lights_off
      turn_off:
        - service: automation.turn_off
          data:
            entity_id: automation.kitchen_lights_on
        - service: automation.turn_off
          data:
            entity_id: automation.kitchen_lights_off
      value_template: >
        {{ is_state('automation.kitchen_lights_on', 'on') and is_state('automation.kitchen_lights_off', 'on') }}
      icon_template: mdi:lightbulb-auto
