- platform: group
  unique_id: living_room_docking_station
  name: "Living Room Docking Station"
  entities:
    - switch.switch_10ff
- platform: group
  unique_id: living_room_tv_power
  name: "Living Room TV Power"
  entities:
    - switch.switch_a391
- platform: template
  switches:
    living_room_dashboard_display:
      unique_id: living_room_dashboard_display
      friendly_name: "Living Room Dashboard Display"
      value_template: "{{ is_state('sensor.dashboard_7e2b_displaypower', 'PowerOn') }}"
      turn_on:
        service: button.press
        data:
          entity_id: button.dashboard_7e2b_displaywake
      turn_off:
        service: button.press
        data:
          entity_id: button.dashboard_7e2b_displaysleep
- platform: template
  switches:
    laptop_display:
      unique_id: laptop_display
      friendly_name: "Laptop Display"
      value_template: "{{ is_state('sensor.laptop_5647_displaypower', 'PowerOn') }}"
      turn_on:
        service: button.press
        data:
          entity_id: button.laptop_5647_displaywake
      turn_off:
        service: button.press
        data:
          entity_id: button.laptop_5647_displaysleep
- platform: template
  switches:
    living_room_lights_auto:
      unique_id: living_room_lights_auto
      friendly_name: "Living Room Lights Auto"
      turn_on:
        - service: automation.turn_on
          data:
            entity_id: automation.living_room_lights_on
        - service: automation.turn_on
          data:
            entity_id: automation.living_room_lights_off
      turn_off:
        - service: automation.turn_off
          data:
            entity_id: automation.living_room_lights_on
        - service: automation.turn_off
          data:
            entity_id: automation.living_room_lights_off
      value_template: >
        {{ is_state('automation.living_room_lights_on', 'on') and is_state('automation.living_room_lights_off', 'on') }}
      icon_template: mdi:lightbulb-auto
