- platform: group
  unique_id: living_room_docking_station
  name: "Living Room Docking Station"
  entities:
    - switch.switch_10ff
- platform: group
  unique_id: living_room_tv_power
  name: "Living Room TV Power"
  entities:
    - switch.switch_a391
