- platform: group
  unique_id: living_room_docking_station
  name: "Living Room Docking Station"
  entities:
    - switch.switch_10ff
- platform: group
  unique_id: living_room_tv_power
  name: "Living Room TV Power"
  entities:
    - switch.switch_a391
- platform: template
  switches:
    living_room_dashboard_display:
      unique_id: living_room_dashboard_display
      friendly_name: "Living Room Dashboard Display"
      value_template: "{{ is_state('sensor.dashboard_7e2b_displaypower', 'PowerOn') }}"
      turn_on:
        service: button.press
        data:
          entity_id: button.dashboard_7e2b_displaywake
      turn_off:
        service: button.press
        data:
          entity_id: button.dashboard_7e2b_displaysleep
- platform: template
  switches:
    laptop_display:
      unique_id: laptop_display
      friendly_name: "Laptop Display"
      value_template: "{{ is_state('sensor.laptop_5647_displaypower', 'PowerOn') }}"
      turn_on:
        service: button.press
        data:
          entity_id: button.laptop_5647_displaywake
      turn_off:
        service: button.press
        data:
          entity_id: button.laptop_5647_displaysleep
- platform: template
  switches:
    living_room_lights_auto:
      unique_id: living_room_lights_auto
      friendly_name: "Living Room Lights Auto"
      turn_on:
        - service: automation.turn_on
          data:
            entity_id: automation.living_room_lights_on
        - service: automation.turn_on
          data:
            entity_id: automation.living_room_lights_off
      turn_off:
        - service: automation.turn_off
          data:
            entity_id: automation.living_room_lights_on
        - service: automation.turn_off
          data:
            entity_id: automation.living_room_lights_off
      value_template: >
        {{ is_state('automation.living_room_lights_on', 'on') and is_state('automation.living_room_lights_off', 'on') }}
      icon_template: mdi:lightbulb-auto
- platform: template
  switches:
    living_room_fan_off:
      friendly_name: "Living Room Fan Off"
      value_template: "{{ is_state('fan.living_room_fan', 'off') }}"
      turn_on:
        service: fan.turn_off
        target:
          entity_id: fan.living_room_fan
      turn_off:
        service: fan.turn_on
        target:
          entity_id: fan.living_room_fan
      icon_template: mdi:fan-off

    living_room_fan_speed_1:
      friendly_name: "Living Room Fan Speed 1"
      value_template: "{{ is_state('fan.living_room_fan', 'on') and state_attr('fan.living_room_fan', 'percentage') == 33 }}"
      turn_on:
        service: fan.set_percentage
        target:
          entity_id: fan.living_room_fan
        data:
          percentage: 33
      turn_off:
        service: fan.turn_off
        target:
          entity_id: fan.living_room_fan
      icon_template: mdi:fan-speed-1

    living_room_fan_speed_2:
      friendly_name: "Living Room Fan Speed 2"
      value_template: "{{ is_state('fan.living_room_fan', 'on') and state_attr('fan.living_room_fan', 'percentage') == 66 }}"
      turn_on:
        service: fan.set_percentage
        target:
          entity_id: fan.living_room_fan
        data:
          percentage: 66
      turn_off:
        service: fan.turn_off
        target:
          entity_id: fan.living_room_fan
      icon_template: mdi:fan-speed-2

    living_room_fan_speed_3:
      friendly_name: "Living Room Fan Speed 3"
      value_template: "{{ is_state('fan.living_room_fan', 'on') and state_attr('fan.living_room_fan', 'percentage') == 100 }}"
      turn_on:
        service: fan.set_percentage
        target:
          entity_id: fan.living_room_fan
        data:
          percentage: 100
      turn_off:
        service: fan.turn_off
        target:
          entity_id: fan.living_room_fan
      icon_template: mdi:fan-speed-3

    living_room_fan_oscillating:
      friendly_name: "Living Room Fan Oscillating"
      value_template: "{{ is_state_attr('fan.living_room_fan', 'oscillating', true) }}"
      turn_on:
        service: fan.oscillate
        target:
          entity_id: fan.living_room_fan
        data:
          oscillating: true
      turn_off:
        service: fan.oscillate
        target:
          entity_id: fan.living_room_fan
        data:
          oscillating: false
      icon_template: >
        {% if is_state_attr('fan.living_room_fan', 'oscillating', true) %}
          mdi:arrow-oscillating
        {% else %}
          mdi:arrow-oscillating-off
        {% endif %}
