esphome:
  name: "btn-d669"
  friendly_name: "btn-d669"

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "dCwxOBnz5OMv1IPXwHZEH9MR6g2sxVuP6NHipB0qxOw="

ota:
  - platform: esphome
    password: "71bd964ba1b72d9c3dd26295d9ca0d4e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "8xLEs1x4V1Yo"

captive_portal:
    
i2c:
  sda: D1
  scl: D2

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    # address: 0x3F
    lambda: |-
      it.strftime("It is %H:%M on %d.%m.%Y", id(my_time).now());

time:
- platform: homeassistant
  id: my_time