substitutions:
  name: "switch-325a"

esphome:
  name: ${name}
  friendly_name: ${name}
  min_version: 2024.6.0

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow provisioning Wi-Fi via serial
improv_serial:

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password
    id: ota_pass

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password


# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

switch:
  - platform: gpio
    pin: GPIO0
    name: "Switch"
    inverted: true