- platform: template
  fans:
    bathroom_fan:
      friendly_name: "Bathroom Fan"
      unique_id: bathroom_fan
      value_template: "{{ states('light.light_b55c_light_1') == 'on' }}"
      turn_on:
        action: light.turn_on
        target:
          entity_id: light.light_b55c_light_1
      turn_off:
        action: light.turn_off
        target:
          entity_id: light.light_b55c_light_1
      speed_count: 1
