- platform: group
  unique_id: "garden_lights_on_button_pressed"
  name: "Garden Lights On Button Pressed"
  entities:
    - event.btn_f695_button_3
- platform: group
  unique_id: "garden_lights_off_button_pressed"
  name: "Garden Lights Off Button Pressed"
  entities:
    - event.btn_f695_button_4
