blueprint:
  name: Occupancy Controlled Device
  description: Automates entities based on occupancy and daylight sensors
  domain: automation
  homeassistant:
    min_version: "2024.8.0"
  input:
    occupancy_sensor:
      name: Occupancy Sensor
      description: The sensor detecting occupancy
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class: occupancy
    daylight_sensor:
      name: Daylight Sensor
      description: The sensor detecting daylight
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class: light
      default: ""
    default_scene_occupied:
      name: Default Scene (Occupied)
      description: The scene to activate when occupancy is detected
      selector:
        entity:
          filter:
            domain: scene
    off_delay_duration:
      name: Off Delay
      description: >
        The duration of time to delay before turning off the targets after 
        unoccupied.
      selector:
        duration:
      default:
        hours: 0
        minutes: 2
        seconds: 0

variables:
  # save in variable so that it can be used in templates
  default_scene_occupied: !input default_scene_occupied
  target_entities: "{{ state_attr(default_scene_occupied, 'entity_id') | list }}"
  daylight_sensor: !input daylight_sensor

triggers:
  - alias: Any change in daylight
    trigger: template
    value_template: "{{ daylight_sensor == '' or is_state(daylight_sensor, 'off') }}"
  - alias: Change of occupancy detected to occupancy clear for the specified duration
    trigger: state
    entity_id: !input occupancy_sensor
    from: "on"
    to: "off"
    for: !input off_delay_duration
    id: "occupancy_clear"
  - alias: Change of occupancy clear to occupancy detected.
    trigger: state
    entity_id: !input occupancy_sensor
    from: "off"
    to: "on"
    id: "occupancy_detected"

action:
  - choose:
      # activate default scene on occupancy
      - conditions:
          - alias: >
              Check that triggered by a change in occupancy from clear to 
              detected.
            condition: trigger
            id:
              - "occupancy_detected"
        sequence:
          - action: scene.turn_on
            data: {}
            target:
              entity_id: !input default_scene_occupied

      # turn off when no occupancy for duration
      - conditions:
          - alias: >
              Check that it was triggered by a change in occupancy from 
              detected to clear for specified duration
            condition: trigger
            id:
              - "occupancy_clear"
        sequence:
          - action: homeassistant.turn_off
            target:
              entity_id: "{{ target_entities }}"
