esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  min_version: 2024.7.0

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

i2s_audio:
  i2s_bclk_pin: GPIO6
  i2s_lrclk_pin: GPIO5
  # bits_shift: 8

microphone:
  - platform: i2s_audio
    id: mic
    adc_type: external
    i2s_din_pin: GPIO7
    sample_rate: 24000            # default: 48000
    bits_per_sample: 32bit
    i2s_mode: primary
    channel: left               # default: right

sound_level_meter:
  task_core: 0
  microphone:
    microphone: mic
    bits_per_sample: 32

  # update_interval specifies over which interval to aggregate audio data
  # you can specify default update_interval on top level, but you can also
  # override it further by specifying it on sensor level
  update_interval: 1s           # default: 60s

  # see your mic datasheet to find sensitivity and reference SPL.
  # those are used to convert dB FS to db SPL
  mic_sensitivity: -26dB        # default: empty
  mic_sensitivity_ref: 94dB     # default: empty

  # # additional offset if needed
  # offset: -12dB                   # default: empty

  dsp_filters:
    - type: sos
      id: f_inmp441
      coeffs:
        # INMP441:
        #      b0            b1           b2          a1            a2
        - [ 1.0019784 , -1.9908513  , 0.9889158 , -1.9951786  , 0.99518436]

    - 
      id: f_a
      type: sos
      coeffs:
      
        # A-weighting:
        #       b0           b1            b2             a1            a2
        - [ 0.16999495 ,  0.741029   ,  0.52548885 , -0.11321865 , -0.056549273]
        - [ 1.         , -2.00027    ,  1.0002706  , -0.03433284 , -0.79215795 ]
        - [ 1.         , -0.709303   , -0.29071867 , -1.9822421  ,  0.9822986  ]

  sensors:
    - type: eq
      id: LAeq_1s_uncalibrated
      unit_of_measurement: dBA
      update_interval: 1s
      dsp_filters: 
      - f_inmp441
      - f_a
      internal: True

sensor:
  - platform: copy
    source_id: LAeq_1s_uncalibrated
    name: "LAeq,1s"
    id: LAeq_1s
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters:
      - offset: !lambda return id(calibration_offset).state;

  - platform: copy
    source_id: LAeq_1s
    id: LAeq_1s_linear
    internal: True
    filters:
      - lambda: |-
          if (isnan(x)) {
            return NAN;
          } else {
            return pow(10, x / 10.0);
          }
  - platform: copy
    source_id: LAeq_1s_linear
    id: LAeq_10s_linear
    internal: True
    accuracy_decimals: 2
    filters: 
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
  - platform: copy
    source_id: LAeq_1s_linear
    id: LAeq_1min_linear
    internal: True
    accuracy_decimals: 2
    filters: 
      - sliding_window_moving_average:
          window_size: 60
          send_every: 1
  - platform: copy
    source_id: LAeq_1s_linear
    id: LAeq_5min_linear
    internal: True
    accuracy_decimals: 2
    filters: 
      - sliding_window_moving_average:
          window_size: 300
          send_every: 1
  - platform: copy
    source_id: LAeq_10s_linear
    id: LAeq_10s
    name: "LAeq,10s"
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters: 
      - lambda: |-
          if (isnan(x) || x <= 0.0) {
            return NAN;
          } else {
            return 10.0 * log10(x);
          }
      - or:
        - delta: 0.1
        - heartbeat: 60s # at least every 60 s
  - platform: copy
    source_id: LAeq_1min_linear
    id: LAeq_1min
    name: "LAeq,1min"
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters: 
      - lambda: |-
          if (isnan(x) || x <= 0.0) {
            return NAN;
          } else {
            return 10.0 * log10(x);
          }
      - or:
        - delta: 0.1
        - heartbeat: 60s # at least every 60 s
  - platform: copy
    source_id: LAeq_5min_linear
    id: LAeq_5min
    name: "LAeq,5min"
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters: 
      - lambda: |-
          if (isnan(x) || x <= 0.0) {
            return NAN;
          } else {
            return 10.0 * log10(x);
          }
      - or:
        - delta: 0.1
        - heartbeat: 60s # at least every 60 s
  - platform: copy
    source_id: LAeq_1s
    id: LA50_10s
    name: "LA50,10s"
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters: 
      - quantile:
          window_size: 10
          send_every: 1
          quantile: 0.5
      - or:
        - delta: 0.1
        - heartbeat: 60s # at least every 60 s
  - platform: copy
    source_id: LAeq_1s
    id: LA10_10s
    name: "LA10,10s"
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters: 
      - quantile:
          window_size: 10
          send_every: 1
          quantile: 0.1
      - or:
        - delta: 0.1
        - heartbeat: 60s # at least every 60 s
  - platform: copy
    source_id: LAeq_1s
    id: LA90_10s
    name: "LA90,10s"
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters: 
      - quantile:
          window_size: 10
          send_every: 1
          quantile: 0.9
      - or:
        - delta: 0.1
        - heartbeat: 60s # at least every 60 s
  - platform: copy
    source_id: LAeq_1s
    id: LA50_1min
    name: "LA50,1min"
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters: 
      - quantile:
          window_size: 60
          send_every: 1
          quantile: 0.5
      - or:
        - delta: 0.1
        - heartbeat: 60s # at least every 60 s
  - platform: copy
    source_id: LAeq_1s
    id: LA10_1min
    name: "LA10,1min"
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters: 
      - quantile:
          window_size: 60
          send_every: 1
          quantile: 0.1
      - or:
        - delta: 0.1
        - heartbeat: 60s # at least every 60 s
  - platform: copy
    source_id: LAeq_1s
    id: LA90_1min
    name: "LA90,1min"
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters: 
      - quantile:
          window_size: 60
          send_every: 1
          quantile: 0.9
      - or:
        - delta: 0.1
        - heartbeat: 60s # at least every 60 s
  - platform: copy
    source_id: LAeq_1s
    id: LA50_5min
    name: "LA50,5min"
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters: 
      - quantile:
          window_size: 300
          send_every: 1
          quantile: 0.5
      - or:
        - delta: 0.1
        - heartbeat: 60s # at least every 60 s
  - platform: copy
    source_id: LAeq_1s
    id: LA10_5min
    name: "LA10,5min"
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters: 
      - quantile:
          window_size: 300
          send_every: 1
          quantile: 0.1
      - or:
        - delta: 0.1
        - heartbeat: 60s # at least every 60 s
  - platform: copy
    source_id: LAeq_1s
    id: LA90_5min
    name: "LA90,5min"
    accuracy_decimals: 2
    device_class: sound_pressure
    state_class: measurement
    unit_of_measurement: "dBA"
    icon: "mdi:waveform"
    filters: 
      - quantile:
          window_size: 300
          send_every: 1
          quantile: 0.9
      - or:
        - delta: 0.1
        - heartbeat: 60s # at least every 60 s
  

number:
  - platform: template
    name: "Calibration Offset"
    id: calibration_offset
    optimistic: true
    min_value: -20
    max_value: 20
    initial_value: 0.0
    step: 0.1
    restore_value: true
    unit_of_measurement: "dBA"
    mode: box
    entity_category: config
