- platform: min_max
  unique_id: bathroom_illuminance
  name: "Bathroom Illuminance"
  type: mean
  entity_ids:
    - sensor.occupancy_715f_illuminance
- platform: min_max
  unique_id: bathroom_temperature
  name: "Bathroom Temperature"
  type: mean
  entity_ids:
    - sensor.therm_d7f6_temperature
- platform: min_max
  unique_id: bathroom_relative_humidity
  name: "Bathroom Relative Humidity"
  type: mean
  entity_ids:
    - sensor.therm_d7f6_relative_humidity
- platform: statistics
  name: "Bathroom Relative Humidity Median"
  unique_id: bathroom_relative_humidity_median
  entity_id: sensor.bathroom_relative_humidity
  max_age:
    hours: 24
  state_characteristic: median
