- platform: min_max
  unique_id: bedroom_temperature
  name: "Bedroom Temperature"
  type: mean
  entity_ids:
    - sensor.fan_1d90_temperature
    - sensor.clock_3006_temperature
- platform: min_max
  unique_id: bedroom_bed_temperature
  name: "Bedroom Bed Temperature"
  type: mean
  entity_ids:
    - sensor.therm_d71e_temperature
- platform: min_max
  unique_id: bedroom_relative_humidity
  name: "Bedroom Relative Humidity"
  type: mean
  entity_ids:
    - sensor.fan_1d90_humidity
    - sensor.clock_3006_humidity
- platform: min_max
  unique_id: bedroom_illuminance
  name: "Bedroom Illuminance"
  type: mean
  entity_ids:
    - sensor.occupancy_249b_light_sensor_light_level
- platform: min_max
  unique_id: bedroom_pm_10
  name: "Bedroom PM10"
  type: mean
  entity_ids:
    - sensor.fan_1d90_pm_10
- platform: min_max
  unique_id: bedroom_pm_2_5
  name: "Bedroom PM2.5"
  type: mean
  entity_ids:
    - sensor.fan_1d90_pm_2_5
- platform: min_max
  unique_id: bedroom_volatile_organic_compounds
  name: "Bedroom Volatile Organic Compounds"
  type: mean
  entity_ids:
    - sensor.fan_1d90_volatile_organic_compounds
- platform: min_max
  unique_id: bedroom_nitrogen_dioxide
  name: "Bedroom Nitrogen Dioxide"
  type: mean
  entity_ids:
    - sensor.fan_1d90_nitrogen_dioxide
- platform: min_max
  unique_id: bedroom_sound_pressure
  name: "Bedroom Sound Pressure"
  type: mean
  entity_ids:
    - sensor.clock_3006_sound_pressure
