- platform: min_max
  unique_id: home_temperature
  name: "Home Temperature"
  type: mean
  entity_ids:
    - sensor.living_room_temperature
    - sensor.bedroom_temperature
    - sensor.bathroom_temperature
    - sensor.kitchen_temperature

- platform: min_max
  unique_id: home_relative_humidity
  name: "Home Relative Humidity"
  type: mean
  entity_ids:
    - sensor.bedroom_relative_humidity
    - sensor.bathroom_relative_humidity
    - sensor.kitchen_relative_humidity

- platform: min_max
  unique_id: home_atmospheric_pressure
  name: "Home Atmospheric Pressure"
  type: mean
  entity_ids:
    - sensor.therm_dc8d_atmospheric_pressure

- platform: min_max
  unique_id: home_mains_voltage
  name: "Home Mains Voltage"
  type: mean
  entity_ids:
    - sensor.switch_2653_voltage
    - sensor.switch_50b5_voltage
    - sensor.switch_8761_voltage
    - sensor.switch_b941_voltage
    - sensor.switch_6ee3_voltage
    - sensor.switch_bd81_voltage
    - sensor.climate_0000_voltage
