- platform: min_max
  unique_id: kitchen_illuminance
  name: "Kitchen Illuminance"
  type: mean
  entity_ids:
    - sensor.occupancy_952c_illuminance

- platform: min_max
  unique_id: kitchen_temperature
  name: "Kitchen Temperature"
  type: mean
  entity_ids:
    - sensor.therm_dc8d_temperature

- platform: min_max
  unique_id: kitchen_relative_humidity
  name: "Kitchen Relative Humidity"
  type: mean
  entity_ids:
    - sensor.therm_dc8d_relative_humidity
