- platform: min_max
  unique_id: living_room_illuminance
  name: "Living Room Illuminance"
  type: mean
  entity_ids:
    - sensor.occupancy_7ae8_light_sensor_light_level

- platform: min_max
  unique_id: living_room_temperature
  name: "Living Room Temperature"
  type: mean
  entity_ids:
    - sensor.fan_6ab8_temperature
    - sensor.therm_b31f_temperature_1
    - sensor.therm_977c_temperature
    - sensor.climate_44a4_temperature

- platform: min_max
  unique_id: living_room__radiator_temperature
  name: "Living Room Radiator Temperature"
  type: mean
  entity_ids:
    - sensor.therm_b31f_temperature_2

- platform: min_max
  unique_id: living_room_desk_temperature
  name: "Living Room Desk Temperature"
  type: mean
  entity_ids:
    - sensor.therm_b31f_temperature_1

- platform: min_max
  unique_id: living_room_sofa_temperature
  name: "Living Room Sofa Temperature"
  type: mean
  entity_ids:
    - sensor.therm_977c_temperature

- platform: history_stats
  name: Living Room Sofa Occupancy Ratio
  unique_id: living_room_sofa_occupancy_ratio
  entity_id: binary_sensor.living_room_sofa_occupancy
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    minutes: 15

- platform: history_stats
  name: Living Room Desk Occupancy Ratio
  unique_id: living_room_desk_occupancy_ratio
  entity_id: binary_sensor.living_room_desk_occupancy
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    minutes: 15
