- platform: min_max
  unique_id: outdoor_temperature
  name: "Outdoor Temperature"
  type: mean
  entity_ids:
    - sensor.temperature
- platform: min_max
  unique_id: outdoor_relative_humidity
  name: "Outdoor Relative Humidity"
  type: mean
  entity_ids:
    - sensor.humidity
