substitutions:
  device_name: btn-74ad

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  min_version: 2024.7.0

esp8266:
  board: esp01_1m

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
    id: ota_pass

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: !secret wifi_fallback_ap_password

captive_portal:

event:
  - platform: template
    name: Button 1 Pressed
    id: button_1_pressed
    device_class: button
    event_types:
      - short_press
      - long_press
  - platform: template
    name: Button 2 Pressed
    id: button_2_pressed
    device_class: button
    event_types:
      - short_press
      - long_press
  - platform: template
    name: Button 3 Pressed
    id: button_3_pressed
    device_class: button
    event_types:
      - short_press
      - long_press
  - platform: template
    name: Button 4 Pressed
    id: button_4_pressed
    device_class: button
    event_types:
      - short_press
      - long_press
  - platform: template
    name: Button 5 Pressed
    id: button_5_pressed
    device_class: button
    event_types:
      - short_press
      - long_press

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
    name: "Button 1"
    id: button_1
    filters:
      - invert:
      - delayed_on: 10ms
      - delayed_off: 10ms
    internal: true
    on_press:
      then:
        - wait_until:
            condition:
              binary_sensor.is_off: button_1
            timeout: 1s
        - if:
            condition:
              binary_sensor.is_on: button_1
            then:
              - event.trigger:
                  id: button_1_pressed
                  event_type: "long_press"
            else:
              - event.trigger:
                  id: button_1_pressed
                  event_type: "short_press"
  - platform: gpio
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
    name: "Button 2"
    id: button_2
    filters:
      - invert:
      - delayed_on: 10ms
      - delayed_off: 10ms
    internal: true
    on_press:
      then:
        - wait_until:
            condition:
              binary_sensor.is_off: button_2
            timeout: 1s
        - if:
            condition:
              binary_sensor.is_on: button_2
            then:
              - event.trigger:
                  id: button_2_pressed
                  event_type: "long_press"
            else:
              - event.trigger:
                  id: button_2_pressed
                  event_type: "short_press"
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
    name: "Button 3"
    id: button_3
    filters:
      - invert:
      - delayed_on: 10ms
      - delayed_off: 10ms
    internal: true
    on_press:
      then:
        - wait_until:
            condition:
              binary_sensor.is_off: button_3
            timeout: 1s
        - if:
            condition:
              binary_sensor.is_on: button_3
            then:
              - event.trigger:
                  id: button_3_pressed
                  event_type: "long_press"
            else:
              - event.trigger:
                  id: button_3_pressed
                  event_type: "short_press"
  - platform: gpio
    pin:
      number: GPIO2
      mode:
        input: true
        pullup: true
    name: "Button 4"
    id: button_4
    filters:
      - invert:
      - delayed_on: 10ms
      - delayed_off: 10ms
    internal: true
    on_press:
      then:
        - wait_until:
            condition:
              binary_sensor.is_off: button_4
            timeout: 1s
        - if:
            condition:
              binary_sensor.is_on: button_4
            then:
              - event.trigger:
                  id: button_4_pressed
                  event_type: "long_press"
            else:
              - event.trigger:
                  id: button_4_pressed
                  event_type: "short_press"
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
    name: "Button 5"
    id: button_5
    filters:
      - invert:
      - delayed_on: 10ms
      - delayed_off: 10ms
    internal: true
    on_press:
      then:
        - wait_until:
            condition:
              binary_sensor.is_off: button_5
            timeout: 1s
        - if:
            condition:
              binary_sensor.is_on: button_5
            then:
              - event.trigger:
                  id: button_5_pressed
                  event_type: "long_press"
            else:
              - event.trigger:
                  id: button_5_pressed
                  event_type: "short_press"