substitutions:
  device_name: gas-f1e8

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  min_version: 2024.7.0
  platformio_options:
    board_build.flash_mode: dio
  project: 
    name: Screek.CO2_Sensor
    version: SCO2-1

esp32:
  board: lolin_c3_mini
  framework:
    type: arduino
    version: 2.0.7
    platform_version: 6.0.1

external_components:
  - source:
      type: git
      url: https://github.com/screekworkshop/custom_components_support_for_screek_2a
      ref: main
    components: [uart]

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
    id: ota_pass

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: !secret wifi_fallback_ap_password

web_server:
  port: 80

captive_portal:

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_a

sensor:
  - platform: scd4x
    update_interval: 1s
    co2:
      name: "CO2"
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
        - round: 0
        - or:
          - delta: 5 
          - heartbeat: 60s # at least every 60 s
      
    temperature:
      name: "Reference Temperature"
      entity_category: "diagnostic"
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
        - round: 1 # will round to 1 decimal place
        - or:
          - delta: 0.1 # only send updated value on change >0.1, or
          - heartbeat: 60s # at least every 60 s
    
    humidity:
      name: "Reference Relative Humidity"
      entity_category: "diagnostic"
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
        - round: 0
        - or:
          - delta: 1 
          - heartbeat: 60s # at least every 60 s

light:
  - platform: status_led
    name: sys_status
    pin: 
      number: GPIO12
      ignore_pin_validation_error: true
    internal: True
    restore_mode: ALWAYS_OFF
  - platform: status_led
    name: sys_status
    pin: 
      number: GPIO13
      ignore_pin_validation_error: true
    internal: True
    restore_mode: ALWAYS_OFF

