substitutions:
  device_name: "light-a3a0"

packages:
  - !include common/api.yaml
  - !include common/logger.yaml
  - !include common/ota.yaml
  - !include common/wifi.yaml
  - !include common/improv-esp32.yaml
  - !include common/web-server.yaml

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  min_version: 2024.7.0

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    type: esp-idf

# SK6812 RGBW configuration
light:
  - platform: esp32_rmt_led_strip
    chipset: SK6812
    rgb_order: GRB
    is_rgbw: True
    pin: GPIO10
    num_leds: 209
    id: rgbwlight
    name: "Light"
    restore_mode: RESTORE_AND_ON
    effects:
      - addressable_twinkle:
          name: "Twinkle 15%"
          twinkle_probability: 15%
          progress_interval: 100ms
      - addressable_twinkle:
          name: "Twinkle 25%"
          twinkle_probability: 25%
          progress_interval: 100ms
      - addressable_twinkle:
          name: "Twinkle 35%"
          twinkle_probability: 35%
          progress_interval: 100ms

sensor:
  - platform: internal_temperature
    name: "CPU Temperature"
    update_interval: 60s
    on_value:
      then:
        # Turn off the light internal CPU temp reaches 60 deg C
        - if:
            condition:
              lambda: 'return x >= 60.0;'
            then:
              - light.turn_off: rgbwlight
              - logger.log:
                  format: "CPU temperature exceeded 60°C. Turning off the light."
                  level: ERROR
