substitutions:
  device_name: light-638a

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  on_boot:
    priority: 900
    then:
      - delay: 0.5s

esp8266:
  board: esp01_1m
  restore_from_flash: true

preferences:
  flash_write_interval: 5s

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret wifi_fallback_ap_password

captive_portal:

# Configure the SM2135 component
# https://esphome.io/components/output/sm2135.html
# Tasmota config
# https://github.com/arendst/Tasmota/blob/development/tasmota/tasmota_xlgt_light/xlgt_04_sm2135.ino
# https://templates.blakadder.com/lsc_smart_connect_MR16.html
sm2135:
  data_pin: GPIO12 
  clock_pin: GPIO14
  rgb_current: 20mA
  cw_current: 15mA
  separate_modes: true

# Configure individual outputs for each channel
output:
  - platform: sm2135
    id: output_green
    channel: 0
    min_power: 0.005
    max_power: 0.8
    zero_means_zero: true
  - platform: sm2135
    id: output_red
    channel: 1
    min_power: 0.005
    max_power: 0.8
    zero_means_zero: true
  - platform: sm2135
    id: output_blue
    channel: 2
    min_power: 0.005
    max_power: 0.8
    zero_means_zero: true
  - platform: sm2135
    id: output_cold_white
    channel: 4
    min_power: 0.005
    max_power: 0.8
    zero_means_zero: true
  - platform: sm2135
    id: output_warm_white
    channel: 3
    min_power: 0.005
    max_power: 0.8
    zero_means_zero: true

# Define a light component to control the outputs
light:
  - platform: cwww
    name: "Light"
    # red: output_red
    # green: output_green
    # blue: output_blue
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 4000 K
    warm_white_color_temperature: 2200 K
    restore_mode: RESTORE_AND_ON 
    # color_interlock: true
    # gamma_correct: 1.0