substitutions:
  device_name: light-4da4

packages:
  - !include common/api.yaml
  - !include common/logger.yaml
  - !include common/ota.yaml
  - !include common/wifi.yaml
  - !include common/improv-esp32.yaml
  - !include common/web-server.yaml

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  min_version: 2024.11.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

output:
  - platform: ledc
    pin: GPIO4
    id: gpio_light
    frequency: "100Hz"
    max_power: 0.5
    min_power: 0.001
    zero_means_zero: True
    channel: 2

light:
  - platform: monochromatic
    output: gpio_light
    name: "Light"
    id: light_control

binary_sensor:
  - platform: gpio
    pin: GPIO3
    name: "Button"
    filters:
      - delayed_on: 5ms
    internal: True
    on_press:
      - lambda: |-
          auto brightness = id(light_control).current_values.get_brightness();
          if (!id(light_control).current_values.is_on() || brightness < 0.33) {
            auto call = id(light_control).turn_on();
            call.set_brightness(0.33);
            call.set_transition_length(100);
            call.perform();
          } else if (brightness < 0.66) {
            auto call = id(light_control).turn_on();
            call.set_brightness(0.66);
            call.set_transition_length(100);
            call.perform();
          } else if (brightness < 1.0) {
            auto call = id(light_control).turn_on();
            call.set_brightness(1.0);
            call.set_transition_length(100);
            call.perform();
          } else {
            auto call = id(light_control).turn_off();
            call.set_transition_length(100);
            call.perform();
          }