substitutions:
  device_name: light-03f8

packages:
  - !include common/api.yaml
  - !include common/logger.yaml
  - !include common/ota.yaml
  - !include common/wifi.yaml
  - !include common/web-server.yaml
  - !include common/ledvance-smart-table-frame.yaml
