esphome:
  name: occupancy-e58c
  friendly_name: occupancy-e58c
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: !secret wifi_fallback_ap_password

captive_portal:

# Example configuration entry for ESP32
i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  id: bus_a

sensor:
  - platform: vl53l0x
    id: distance_sensor
    name: "Distance"
    address: 0x29
    update_interval: 0.1s
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
      - round: 2
      - or:
        - delta: 0.01 # only send updated value on change >0.01, or
        - heartbeat: 60s # at least every 60 s
    entity_category: diagnostic

binary_sensor:
  - platform: template
    name: "Occupancy"
    device_class: occupancy
    lambda: |-
      if (!isnan(id(distance_sensor).state) && id(distance_sensor).state > 0.1 && id(distance_sensor).state < 1.0) {
        return true;
      } else {
        return false;
      }
    filters:
      - delayed_on: 0.5s
      - delayed_off: 2s