# Derived from https://github.com/bruvv/LILYGO-T-Higrow-Esphome

substitutions:
  device_name: "plant-735c"
  project_version: "1.1"
  moisture_min: "2.84"
  moisture_max: "1.39"
  conductivity_min: "0.075"
  conductivity_max: "0.25"
  update_interval: "10s"
  # Uncomment run_duration and sleep_duration if you want to use deepsleep
  # set how long to stay awake - NOT less then 10sec
  # run_duration: 11s
  # set how long to sleep in minutes
  # sleep_duration: 60min

esphome:
  name: "${device_name}"
  friendly_name: "${device_name}"
  min_version: 2024.7.0
  on_boot:
    priority: 240
    then:
      - wait_until:
          condition:
            wifi.connected:
          timeout: 10s
  on_shutdown:
    then:
      - switch.turn_off: spower

esp32:
  board: lolin_d32

logger:

improv_serial:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: !secret wifi_fallback_ap_password

captive_portal:

i2c:
  sda: 25
  scl: 26
  scan: true
  id: bus_a
  setup_priority: -200

switch:
  # Power Switch
  - platform: gpio
    name: "Power switch"
    pin:
      number: 4
      mode: INPUT_PULLUP
    id: spower
    restore_mode: ALWAYS_ON
    internal: true
    setup_priority: 1000

sensor:
  - platform: dht
    pin: 16
    temperature:
      name: "Temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
      state_class: "measurement"
      accuracy_decimals: 1
    humidity:
      name: "Relative Humidity"
      unit_of_measurement: "%"
      icon: "mdi:cloud-percent"
      device_class: "humidity"
      state_class: "measurement"
      accuracy_decimals: 1
    setup_priority: -100
    update_interval: ${update_interval}
  # Soil humidity %
  - platform: adc
    pin: GPIO32
    name: 'Soil Moisture'
    icon: 'mdi:watering-can'
    update_interval: ${update_interval}
    attenuation: 11db
    accuracy_decimals: 2 # comment for calibration
    unit_of_measurement: '%' # comment for calibration
    device_class: 'moisture'
    state_class: 'measurement'
    # unit_of_measurement: "V" # uncomment for calibration
    filters: # comment when calibrating
      - calibrate_linear: # comment when calibrating
          # Map 0.0 (from sensor) to 0.0 (true value)
          - ${moisture_min} -> 0.0 # comment when calibrating
          - ${moisture_max} -> 100.0 # comment when calibrating

  # Fertilizer sensor
  - platform: adc
    pin: GPIO34
    name: 'Soil Conductivity'
    icon: 'mdi:flower'
    update_interval: ${update_interval}
    accuracy_decimals: 2 # comment for calibration
    unit_of_measurement: 'µS/cm' # comment when calibrating
    # device_class: '' # for now home assistant does not support this class
    state_class: 'measurement'
    # unit_of_measurement: "V" # uncomment for raw data
    filters: # comment when calibrating
      - calibrate_linear: # comment when calibrating
          # Map 0.0 (from sensor) to 0.0 (true value)
          - ${conductivity_min} -> 0.0 # comment when calibrating
          - ${conductivity_max} -> 100.0 # comment when calibrating

  # Lux sensor
  - platform: bh1750
    i2c_id: bus_a
    name: 'Illuminance'
    address: 0x23
    unit_of_measurement: 'lx'
    icon: 'mdi:white-balance-sunny'
    device_class: 'illuminance'
    state_class: 'measurement'
    setup_priority: -300
    update_interval: ${update_interval}
    # convert to illuminance
    # filters:
    #   - lambda: |-
    #       return x * 200.0;

  # Battery %
  - platform: adc
    pin:
      number: 33
    name: "Battery"
    attenuation: 12db
    accuracy_decimals: 2
    unit_of_measurement: "%"
    filters:
      - multiply: 2
      - calibrate_linear:
          - 3.18 -> 0.0
          - 4.20 -> 100.0
      - clamp: 
          min_value: 0.0
          max_value: 100.0
    update_interval: ${update_interval}
    entity_category: diagnostic
