substitutions:
  device_name: "spl-88e8"

external_components:
  - source: github://stas-sl/esphome-sound-level-meter

packages:
  - !include common/api.yaml
  - !include common/logger.yaml
  - !include common/ota.yaml
  - !include common/wifi.yaml
  - !include common/improv-esp32.yaml
  - !include common/web-server.yaml
  - !include common/esp-spl.yaml
