substitutions:
  device_name: "spl-5bd8"

packages:   # as a list
  - !include common/api.yaml
  - !include common/logger.yaml
  - !include common/ota.yaml
  - !include common/wifi.yaml
  - !include common/improv-esp32.yaml
  - !include common/esp-spl.yaml
