substitutions:
  device_name: "therm-d71e"

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  min_version: 2024.7.0

esp8266:
  board: esp01_1m

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: !secret wifi_fallback_ap_password

captive_portal:

one_wire:
  - platform: gpio
    pin: GPIO13

sensor:
  - platform: dallas_temp
    name: Temperature
    update_interval: 1s
    accuracy_decimals: 1
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
      - round: 1 # will round to 1 decimal place
      - or:
        - delta: 0.1 # only send updated value on change >0.1, or
        - heartbeat: 60s # at least every 60 s


status_led:
  pin:
    number: GPIO2
    inverted: true