substitutions:
  device_name: "therm-dc8d"

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  min_version: 2024.7.0

esp8266:
  board: esp01_1m

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
    id: ota_pass

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: !secret wifi_fallback_ap_password

captive_portal:
 
i2c:
  sda: 14 #D5
  scl: 12 #D6
  scan: true
  id: bus_a

sensor:
  - platform: bmp280_i2c
    address: 0x77
    update_interval: 10s
    temperature:
      name: "BMP temp"
      id: bmp_temp
      oversampling: 2x
      internal: true  # Hide from Home Assistant
    pressure:
      name: "Atmospheric Pressure"

  - platform: aht10
    variant: aht20
    address: 0x38
    update_interval: 10s
    temperature:
      name: "AHT20 temp"
      id: aht20_temp
      accuracy_decimals: 1
      filters:
      - filter_out: 0.0
      - median:
          window_size: 3
          send_every: 3
          send_first_at: 1
      internal: true  # Hide from Home Assistant
    
  # Virtual sensor combining BMP and AHT20 temperatures
  - platform: template
    name: "Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    update_interval: 10s
    lambda: |-
      if (isnan(id(bmp_temp).state)) {
        return id(aht20_temp).state;
      } else if (isnan(id(aht20_temp).state)) {
        return id(bmp_temp).state;
      } else {
        return (id(bmp_temp).state + id(aht20_temp).state) / 2;
      }

status_led:
  pin:
    number: GPIO2
    inverted: true