substitutions:
  device_name: therm-b31f

packages:
  - !include common/api.yaml
  - !include common/logger.yaml
  - !include common/ota.yaml
  - !include common/wifi.yaml
  - !include common/improv-esp8266.yaml

esphome:
  name: ${device_name}
  friendly_name: ${device_name}  
  min_version: 2024.7.0

esp8266:
  board: esp01_1m
    
one_wire:
  - platform: gpio
    pin: GPIO13

sensor:
  - platform: dallas_temp
    address: 0x1f011937b3d80428
    name: "Temperature 1"
    update_interval: 1s
    accuracy_decimals: 1
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
      - round: 1 # will round to 1 decimal place
      - or:
        - delta: 0.1 # only send updated value on change >0.1, or
        - heartbeat: 60s # at least every 60 s
  - platform: dallas_temp
    address: 0x57011937e2f97228
    name: "Temperature 2"
    update_interval: 1s
    accuracy_decimals: 1
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
      - round: 1 # will round to 1 decimal place
      - or:
        - delta: 0.1 # only send updated value on change >0.1, or
        - heartbeat: 60s # at least every 60 s

status_led:
  pin:
    number: GPIO2
    inverted: true