substitutions:
  device_name: "therm-dc8d"

packages:
  - !include common/api.yaml
  - !include common/logger.yaml
  - !include common/ota.yaml
  - !include common/wifi.yaml
  - !include common/improv-esp8266.yaml

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  min_version: 2024.7.0

esp8266:
  board: esp01_1m

i2c:
  - sda: 14 #D5
    scl: 12 #D6
    scan: true
    id: bus_a
  - sda: 9
    scl: 10
    scan: true
    id: bus_b

sensor:
  - platform: bmp280_i2c
    i2c_id: bus_a
    address: 0x77
    update_interval: 1s
    pressure:
      name: "Atmospheric Pressure"
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
        - round: 1 # will round to 1 decimal place
        - or:
          - delta: 0.1 # only send updated value on change >0.1, or
          - heartbeat: 60s # at least every 60 s

  - platform: sht3xd
    i2c_id: bus_b
    address: 0x44  # Default I2C address for SHT31
    update_interval: 1s
    temperature:
      name: "Temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
        - round: 1 # will round to 1 decimal place
        - or:
          - delta: 0.1 # only send updated value on change >0.1, or
          - heartbeat: 60s # at least every 60 s
    humidity:
      name: "Relative Humidity"
      unit_of_measurement: "%"
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
        - round: 1 # will round to 1 decimal place
        - or:
          - delta: 0.1 # only send updated value on change >0.1, or
          - heartbeat: 60s # at least every 60 s

status_led:
  pin:
    number: GPIO2
    inverted: true