substitutions:
  device_name: "therm-dc8d"

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  min_version: 2024.7.0

esp8266:
  board: esp01_1m

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
    id: ota_pass

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: !secret wifi_fallback_ap_password

captive_portal:
 
i2c:
  - sda: 14 #D5
    scl: 12 #D6
    scan: true
    id: bus_a
  - sda: 9
    scl: 10
    scan: true
    id: bus_b

sensor:
  - platform: bmp280_i2c
    i2c_id: bus_a
    address: 0x77
    update_interval: 10s
    pressure:
      name: "Atmospheric Pressure"

  - platform: sht3xd
    i2c_id: bus_b
    temperature:
      name: "Temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 2
    humidity:
      name: "Relative Humidity"
      unit_of_measurement: "%"
      accuracy_decimals: 2
    address: 0x44  # Default I2C address for SHT31
    update_interval: 15s


status_led:
  pin:
    number: GPIO2
    inverted: true